formation_controller_node:
  Kx : 0.2
  Ky : 0.4
  Kphi : 0.0
  control_rate : 100.0
  velocity_limit_lin : 0.2
  velocity_limit_ang : 2.0
  acceleration_limit_lin : 3.0
  acceleration_limit_ang : 3.0